In [1]:
import numpy as np
print('numpy has been imported.')

numpy has been imported.


In [2]:
array1 = np.array([1, 6, 9, 11])

In [3]:
array1

array([ 1,  6,  9, 11])

In [4]:
array1 + 5

array([ 6, 11, 14, 16])

In [5]:
array1 - 9

array([-8, -3,  0,  2])

In [6]:
array1 * 3

array([ 3, 18, 27, 33])

In [7]:
array1 ** 2

array([  1,  36,  81, 121])

In [8]:
a = np.array([1, 3, 5, 7])

In [9]:
b = np.array([3, 5, 7, 7])

In [11]:
a == b

array([False, False, False,  True])

In [12]:
a > b

array([False, False, False, False])